server:
  port: 9090

spring:
  application:
    name: "multiple-datasource-kata"
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
      pool-name: "bca-pool"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: db_migrations
    out-of-order: true
    enabled: true
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN